name: vpn_case
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  # Config
  easy_localization: ^3.0.3
  flutter_svg: ^2.0.7
  flutter_bloc: ^9.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:

  uses-material-design: true

  assets:
    - assets/flags/
    - assets/icons/
    - assets/lang/
